name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy and Strip
      run: |
        mkdir -p dist
        cp build/Build/Products/Release/Swift-Craft-Launcher-CLI dist/scl
        cp -R build/Build/Products/Release/en.lproj dist/
        cp -R build/Build/Products/Release/zh-Hans.lproj dist/
        strip dist/scl
        ls -lh dist/scl

    - name: Copy and Strip
      run: |
        cp build/Build/Products/Release/Swift-Craft-Launcher-CLI scl
        echo "Before strip:"
        ls -lh scl
        strip scl
        echo "After strip:"
        ls -lh scl

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: scl
        path: dist
